version: '3'
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    volumes:
      - .:/opt/spark-apps
    ports:
      - "7077:7077"  # Spark master listens on this port for worker connections
      - "8080:8080"  # Web UI for Spark master
    command: >
      /bin/bash -c "pip install numpy==2.0.2 pandas==2.2.3 pyarrow==17.0.0 pyspark==3.5.3 && /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master"

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077  # This is the correct URL for worker to connect to master
    depends_on:
      - spark-master
    volumes:
      - .:/opt/spark-apps
    ports:
      - "8081:8081"  # Web UI for this worker
    command: >
      /bin/bash -c "pip install numpy==2.0.2 pandas==2.2.3 pyarrow==17.0.0 pyspark==3.5.3 && /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077  # Same as worker-1, this is the master's communication URL
    depends_on:
      - spark-master
    volumes:
      - .:/opt/spark-apps
    ports:
      - "8082:8082"  # Web UI for this worker
    command: >
      /bin/bash -c "pip install numpy==2.0.2 pandas==2.2.3 pyarrow==17.0.0 pyspark==3.5.3 && /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"  

  spark-worker-3:
    image: bitnami/spark:latest
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077  # Same as worker-1, this is the master's communication URL
    depends_on:
      - spark-master
    volumes:
      - .:/opt/spark-apps
    ports:
      - "8083:8083"  # Web UI for this worker
    command: >
      /bin/bash -c "pip install numpy==2.0.2 pandas==2.2.3 pyarrow==17.0.0 pyspark==3.5.3 && /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"          